add timeouts for calls to stripe
wix/libpay-stripe pull request #7
Opened 2018-05-21 14:56 UTC by d12frosted

@artempWix please add take this PR and add tests ❤️

2018-05-21 15:18 UTC, dleshem requested changes
timeouts should be passed in constructor.

2018-05-22 10:15 UTC, artempWix commented
@dleshem, optional constructor parameters were added
now these changes should affect only Cashier (we will pass these timeouts)

2018-05-22 10:20 UTC, dleshem commented
@artempWix Excellent, thanks.

Consider making these arguments `Option[Duration]` instead of `Option[Int]`. You can then pass `Some(2.seconds)` instead of `Some(1000 * 2)` which makes the code more readable.

2018-05-22 10:38 UTC, d12frosted commented on libpay-stripe/src/main/scala/com/wix/pay/stripe/StripeGateway.scala
> +  private implicit class `RequestOptionsTimeoutBuilder`(builder: RequestOptionsBuilder) {
`RequestOptionsTimeoutBuilder`, `maybeTimeout` and `timeout` should be renamed I think :)

2018-05-22 12:51 UTC, dleshem approved these changes

2018-05-25 07:02 UTC, merged